
version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: taxi-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pondytaxi
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - taxi-network

  api:
    build: .
    container_name: taxi-api
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/pondytaxi?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - "8080:8080"
    command: ["/wait-for-it.sh", "mysql:3306", "--", "java", "-jar", "app.jar"]
    networks:
      - taxi-network

networks:
  taxi-network:

volumes:
  mysql-data:
